import FreeCAD as App
doc = App.openDocument(u"cad/turret/turret.FCStd")
doc.recompute(None, True, True)
sheet = doc.getObject("Parameters")
o = doc.getObject("TOWER_L")
print("TOWER_L obj:", o)
s = o.Shape.copy(); s.Placement = o.getGlobalPlacement()
print("ZMin now:", s.BoundBox.ZMin)
tz = float(sheet.get("turret_deck_z0"))
sheet.set("turret_deck_z0", repr(tz+4.0))
doc.recompute(None, True, True)
s = o.Shape.copy(); s.Placement = o.getGlobalPlacement()
print("ZMin +4:", s.BoundBox.ZMin)
sheet.set("turret_deck_z0", repr(tz))
